### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by subins2000** [mirelvt/js-css-tooltip#1]
Thank you for making this ! It's useful for my project

The tooltip's position is wrong if the page has scrolling, because the offset calculation doesn't account scrolling. Would be great if this is fixed.

https://stackoverflow.com/a/38515267

**Comment by mirelvt** [comment]
A new release is available which fixes this issue. Thanks for the feedback.

**Comment by subins2000** [comment]
Thank you !!
