### ISSUE TITLE
Only works with "max-width: 200px" ?

### ISSUE THREAD

**Issue by markteunen65** [mirelvt/js-css-tooltip#2]
Positioning of the tooltip inside the viewport only works when the max-width value in the css file remains unchanged

**Comment by mirelvt** [comment]
Can you explain in which situation it goes wrong? I've tested it by changing the max-width of .tooltip-container to 400px or 600px and it works. I've tested it in the latest browsers of Chrome, Safari, Firefox, Edge.

**Comment by markteunen65** [comment]
Je hebt gelijk, Mirella 👍

Als je in index.html en in tooltip.css de "example-" weglaat, dan werkt het
inderdaad (dus tooltip-example-left wordt gewoon tooltip-left)
Ik had echter de -example classes volledig verwijderd uit de stylesheet.

Mijn excuses en dank voor de mooie, simpele code.

Mvg,
Mark

**Comment by mirelvt** [comment]
Hallo Mark,
Goed om te horen dat het is gelukt. 👍
En bedankt voor het compliment.

Mvg,
Mirella
